# Generated by Django 5.2.17 on 2026-09-23 21:49

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CheckIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(unique=True)),
                ('respuestas', models.JSONField()),
                ('indice', models.PositiveSmallIntegerField()),
                ('nivel', models.CharField(max_length=20)),
                ('creado', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Sesion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.SlugField(unique=True)),
                ('titulo', models.CharField(max_length=120)),
                ('categoria', models.CharField(max_length=40)),
                ('objetivo', models.CharField(max_length=200)),
                ('duracion_min', models.PositiveSmallIntegerField()),
                ('duracion_max', models.PositiveSmallIntegerField()),
                ('intensidad', models.CharField(max_length=40)),
                ('rpe_min', models.PositiveSmallIntegerField()),
                ('rpe_maximo', models.PositiveSmallIntegerField()),
                ('equipo', models.CharField(max_length=120)),
                ('mensaje', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ['rpe_maximo', 'codigo'],
            },
        ),
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('valoracion', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('esfuerzo', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(10)])),
                ('comentario', models.CharField(blank=True, max_length=500)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('sesion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='demo.sesion')),
            ],
            options={
                'ordering': ['-fecha', '-creado'],
            },
        ),
        migrations.CreateModel(
            name='Paso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.PositiveSmallIntegerField()),
                ('contenido', models.CharField(max_length=200)),
                ('duracion_segundos', models.PositiveIntegerField()),
                ('sesion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pasos', to='demo.sesion')),
            ],
            options={
                'ordering': ['orden'],
            },
        ),
    ]
